# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: LiterallyFabian
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Stockholm
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, languages, languages-graphs, editors
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
